---
title: "Replication of Experiment 1A by Young & Saxe (2011, Cognition)"
author: "Kexin Jiang (k3jiang@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

## Introduction

The study investigated the causal effect of agents' intent on moral judgment. It hypothesized that there are distinct moral domains—harm and purity—in which the agent’s innocent intention matters more for the former and less for the latter. Experiment 1A directly examines this hypothesis. The results supported it, showing that purity violations were judged morally worse than harm when both were committed accidentally, while harm was judged worse than purity violations when both were committed intentionally. I chose this study because I have a strong interest in social cognition. Theoretically, the study emphasizes how intent influences our understanding of others' actions, which I find both fascinating and significant for the field. Practically, it serves as a great example of how to uncover distinct cognitive signatures across different domains by manipulating key factors.


This is a between-subjects experiment with six conditions consisting of two factors: intent (intentional vs. accidental) and moral domain (harm vs. incest vs. ingestion). To replicate this experiment, we will collect data from Prolific. During the experiment, participants will first read moral scenarios in the second person tense (e.g., "Your cousin comes over for dinner", provided in the supplementary materials). Then, they will rate the moral wrongness of the action on a 7-point scale, anchored at "not at all morally wrong" (1) to "very morally wrong" (7). For each moral domain, there are two scenarios: harm (allergy, poison), incest (parent, sibling), and ingestion (dog meat, urine). Each scenario has two versions (intentional and accidental), and each participant will see only one version.

The challenge in replicating this experiment might be a lack of experience in collecting online data from Prolific. I hope I can manage the materials counterbalancing right. I will learn a lot.


[Link to the original paper](https://www.sciencedirect.com/science/article/pii/S0010027711001107#s0010)


[Link to the repository](https://github.com/KexinJiang27/Replication-of-Experiment-1A-by-Young-Saxe-2011-Cognition)


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
